import time
import keyboard

print("\n\n\nozpoczynanie sekwencji Pisania...\nMasz 5 sekund aby zaznaczyc pole tekstowe do ktorego ma wbyc wpisywana zawartosc")
time.sleep(2)
print("\n\n\nRozpoczynanie za 3 sekundy\nTekst: FILSONEQ: Zlote Buty")
time.sleep(3)
keyboard.write("Złote Buty, złote chmury")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Jestem tutaj żółty")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Robie papier, robie cash, bo jestem ruudy")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Szukam Buty robie Nuty, jestem też nudny")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Zbieram cash, robie strefe i zabita na EZ")
keyboard.press_and_release("enter")
time.sleep(1.5)
keyboard.write("Wracam z Miasta widzę tutaj dziury")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Idę do sklepu je zwrócić (zwrócić)")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Wracam na chate, patrze no i widze zółte buty")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("No i nie moge już dłużej znosić, ej")
keyboard.press_and_release("enter")
time.sleep(1.5)
keyboard.write("Złote Buty, złote chmury")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Jestem tutaj żółty")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Robie papier, robie cash, bo jestem ruudy")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Złote Buty, złote chmury")
keyboard.press_and_release("enter")
time.sleep(1.5)
keyboard.write("Jestem tutaj żółty")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Robie papier, robie cash, bo jestem ruudy")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Złote Buty, złote chmury")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Jestem tutaj żółty")
keyboard.press_and_release("enter")
time.sleep(1.5)
keyboard.write("Robie papier, robie cash, bo jestem ruudy")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Szukam Buty robie Nuty, jestem też nudny")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Zbieram cash, robie strefe i zabita na EZ")
keyboard.press_and_release("enter")
time.sleep(1.5)
keyboard.write("Widze rok dwadzieścia jeden")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Mam nadzieje że bedzie lepiej")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Zrobiłem zakupy na niedziele")
keyboard.press_and_release("enter")
time.sleep(1.75)
keyboard.write("Jestem Palion ale leje")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Babcia zepsuła mi komputer od krzysia ej")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Zrobiłem zakupy na niedziele")
keyboard.press_and_release("enter")
time.sleep(1.5)
keyboard.write("Złote Buty, złote chmury")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Jestem tutaj żółty")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Robie papier, robie cash, bo jestem ruudy")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Złote Buty, złote chmury")
keyboard.press_and_release("enter")
time.sleep(1.5)
keyboard.write("Jestem tutaj żółty")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Robie papier, robie cash, bo jestem ruudy")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Złote Buty, złote chmury")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Jestem tutaj żółty")
keyboard.press_and_release("enter")
time.sleep(1.5)
keyboard.write("Robie papier, robie cash, bo jestem ruudy")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Szukam Buty robie Nuty, jestem też nudny")
keyboard.press_and_release("enter")
time.sleep(0.75)
keyboard.write("Zbieram cash, robie strefe i zabita na EZ")
keyboard.press_and_release("enter")
time.sleep(1.5)
print("Zakonczono wysylanie piosenki FILSONEQ: Złote Buty")
print("Skrypt wykonany przez 6vz")

